### PR TITLE
Use unwrap() in e2e tests instead of operator ?

### PR DESCRIPTION
**Pull request by kpp**
# Description

We don't need to propagate error. We need an early panic & stop.

### CODE REVIEW

**Comment by jfldde** [comment]
What do we gain from this ? We're already early exiting on any error + displaying backtrace if RUST_BACKTRACE is toggled

**Comment by yaziciahmet** [comment]
Out of curiosity, what was the previous behavior when an error is returned? It could be better to propagate the error to e2e-framework so it can dump all the relevant information about the current test-state. I think e2e-framework also captures panics but I am not exactly sure.

**Comment by kpp** [comment]
> What do we gain from this ? We're already early exiting on any error + displaying backtrace if RUST_BACKTRACE is toggled

I don't need a backtrace of the error, I need a backtrace where it failed in the test + error.

Now this info is lost.

**Comment by yaziciahmet** [comment]
@jfldde it might be cool to remove Result return value from the run_test method, and force panic, and handle the panic on the e2e framework. This way, in the first step we can see the actual stack trace, and e2e-framework can do a graceful shutdown of resources. In the following steps, we can even add metadata information to these panics, such as ran resources, their latest block height etc.

**Comment by kpp** [comment]
Seems like we already propagate backtrace for ? errors. The issue is in asserts

**Pull request closed without merging**
