### PR TITLE
Backport lru deadlock fix

### PR DESCRIPTION
**Pull request by kpp**
# Description

## Linked Issues
- Fixes https://github.com/chainwayxyz/citrea/issues/824

### CODE REVIEW

**Comment by eyusufatik** [comment]
are we sure can remove the mutex inside blockcache

**Comment by kpp** [comment]
Yes

**Comment by rakanalh** [comment]
> are we sure can remove the mutex inside blockcache

I have the same concern.

What is the justification of removing the mutex? I wanted to delay my review just to check why it was there to begin with and what potential race conditions the mutex is avoiding.

**Comment by kpp** [comment]
> What is the justification of removing the mutex?

What is the justification of having the mutex?

**Review by rakanalh — APPROVED** [review]
Apparently, the block cache populates itself through the `provider` internally.

Given that the cache is `LruMap`, this means that race conditions to insert blocks would be basically inserting the same piece of data. Therefore, i see @kpp's point in removing the Mutex. 

Based on @kpp's explanation, the mutex was used to get mutable access to the internal LRU maps rather than borrowing self as mutable. So fixing that makes sense as well.

LGTM.

**Pull request merged**
